apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bn8dvk4wg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bn8dvk4wg-go 
  name: bn8dvk4wg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bn8dvk4wg-go 
